const blank = {
  name: '',
  caste: '',
  concept: '',
  supernal: '',
  physical: {
    strength: 1,
    dexterity: 1,
    stamina: 1,
  },
  social: {
    charisma: 1,
    manipulation: 1,
    appearance: 1,
  },
  mental: {
    perception: 1,
    wits: 1,
    intelligence: 1,
  },
  abilities: {
    archery: 0,
    athletics: 0,
    awareness: 0,
    brawl: 0,
    buereacracy: 0,
    craft: 0,
    dodge: 0,
    integrity: 0,
    investigation: 0,
    larceny: 0,
    linguistics: 0,
    lore: 0,
    martial: 0,
    medicine: 0,
    melee: 0,
    occult: 0,
    performance: 0,
    presence: 0,
    resistance: 0,
    ride: 0,
    socialize: 0,
    stealth: 0,
    survival: 0,
    thrown: 0,
    war: 0,
  },
  willpower: 5,
  essence: {
    rating: 1,
    personal: (blank.essence.rating * 3) + 10,
    peripheral: (blank.essence.rating * 7) + 26,
  },
  parry: 0,
  evasion: 0,
  soak: blank.physical.stamina,
  resolve: 0,
  guile: 0,
  health: {
    '-0': 1,
    '-1': 2,
    '-2': 2,
    '-4': 1,
    incap: 1,
  },
};

module.exports = { blank };
