module.exports = {
  info: {
    Name: '',
    Caste: '',
    Concept: '',
    Supernal: '',
  },
  physical: {
    Strength: 1,
    Dexterity: 1,
    Stamina: 1,
  },
  social: {
    Charisma: 1,
    Manipulation: 1,
    Appearance: 1,
  },
  mental: {
    Perception: 1,
    Wits: 1,
    Intelligence: 1,
  },
  abilities: {
    Archery: 0,
    Athletics: 0,
    Awareness: 0,
    Brawl: 0,
    Buereacracy: 0,
    Craft: 0,
    Dodge: 0,
    Integrity: 0,
    Investigation: 0,
    Larceny: 0,
    Linguistics: 0,
    Lore: 0,
    'Martial Arts': 0,
    Medicine: 0,
    Melee: 0,
    Occult: 0,
    Performance: 0,
    Presence: 0,
    Resistance: 0,
    Ride: 0,
    Socialize: 0,
    Stealth: 0,
    Survival: 0,
    Thrown: 0,
    War: 0,
  },
  Willpower: 5,
  essence: {
    Rating: 1,
    Personal: 13,
    Peripheral: 33,
  },
  Parry: 0,
  Evasion: 0,
  Soak: 1,
  Resolve: 0,
  Guile: 0,
  Health: {
    '-0': 1,
    '-1': 2,
    '-2': 2,
    '-4': 1,
    Incap: 1,
  },
};
