const mongoose = require('mongoose');

module.exports = new mongoose.Schema({
  name: String,
  caste: String,
  concept: String,
  supernal: String,
  Strength: { type: Number, default: 1 }
  Dexterity: { type: Number, default: 1 },
  Stamina: { type: Number, default: 1 },
  Charisma: { type: Number, default: 1 },
  Manipulation: { type: Number, default: 1 },
  Appearance: { type: Number, default: 1 },
  Perception: { type: Number, default: 1 },
  Wits: { type: Number, default: 1 },
  Intelligence: { type: Number, default: 1 },
  Archery: { type: Number, default: 0 },
  Athletics: { type: Number, default: 0 },
  Awareness: { type: Number, default: 0 },
  Brawl: { type: Number, default: 0 },
  Bureaucracy: { type: Number, default: 0 },
  Craft: { type: Number, default: 0 },
  Dodge: { type: Number, default: 0 },
  Integrity: { type: Number, default: 0 },
  Investigation: { type: Number, default: 0 },
  Larceny: { type: Number, default: 0 },
  Linguistics: { type: Number, default: 0 },
  Lore: { type: Number, default: 0 },
  'Martial Arts': { type: Number, default: 0 },
  Medicine: { type: Number, default: 0 },
  Melee: { type: Number, default: 0 },
  Occult: { type: Number, default: 0 },
  Performance: { type: Number, default: 0 },
  Presence: { type: Number, default: 0 },
  Resistance: { type: Number, default: 0 },
  Ride: { type: Number, default: 0 },
  Socialize: { type: Number, default: 0 },
  Stealth: { type: Number, default: 0 },
  Survival: { type: Number, default: 0 },
  Thrown: { type: Number, default: 0 },
  War: { type: Number, default: 0 },
  willpower: { type: Number, default: 5 },
  essence: { type: Number, default: 1 },
  '-0': { type: Number, default: 1 },
  '-1': { type: Number, default: 2 },
  '-2': { type: Number, default: 2 },
  '-4': { type: Number, default: 1 },
  incap: { type: Number, default: 1 },
});
